# Generated by Django 5.1.4 on 2025-01-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='addfav',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='no', max_length=10),
        ),
    ]
