# Generated by Django 5.1.4 on 2025-01-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_addfav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='addfav',
            field=models.CharField(choices=[('No', 'no'), ('Yes', 'yes')], default='No', max_length=10),
        ),
    ]
