# Generated by Django 5.1.4 on 2025-01-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_addfav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='addfav',
            field=models.BooleanField(default=False, max_length=10),
        ),
    ]
