# Generated by Django 5.1.4 on 2025-01-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_addfav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='addfav',
        ),
    ]
