# Generated by Django 5.1.4 on 2025-01-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_addfav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('Published', 'Published')], default='draft', max_length=30),
        ),
    ]
